#!/bin/bash
# Author: B.Segret, v1.9, 17/01/2016
#                   v1.8, 27/10/2014
#                   v1.7,  6/10/2014
# Produces a video from a list of prefixed files
# SYNOPSIS
#      ./prodVideo <pfx> <nbp> <otp>
# DESCRIPTION
#      -> inputs
#         <src> Path & prefix (without "_") of the .jpg files to be considered
#         <otp> Path & prefix of the .flv video to be produced
#      -> <src> files must be prefixed and suffixed: ${pfx}_[a-zA-Z01-9]*.jpg, a suffix
#         after "_" and before ".jpg", must indicate the alphabetical order to
#         concatenate the frames into a video. A temporary folder $(dirname <otp>)/temp
#         will be created, if not existing, and emptied at the end of the job.
#         (!) BUG: "~" not accepted in the paths!
#         Use of MEncoder with lavc options
#         (?) Use of x264 to get compatibility with Flash players

pfx=$1; # path & prefix of pictures
nbp=$2
otp=$3
wdr=$(dirname $otp)/temp

if [ ! -d $wdr ]; then mkdir $wdr; fi

cp $(ls -1 ${pfx}_[a-zA-Z01-9]*.jpg | sort | tail -${nbp}) $wdr
cp $(ls -1 ${pfx}_[a-zA-Z01-9]*.jpg | sort | tail -1) ${otp}.jpg

mencoder mf://$wdr/*.jpg -mf fps=25:type=jpg -ovc lavc -lavcopts vcodec=mpeg4:mbd=2:trell -oac copy -o ${otp}.flv
#x264 --crf 24 -o $otp/$movieprefix.flv $otp/${moviename}.flv

rm -f $wdr/*.jpg

